"""Initial schema

Revision ID: 9b181abbafba
Revises: 
Create Date: 2026-02-12 02:57:29.738710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b181abbafba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('livechat_agent_id', sa.String(length=255), nullable=False),
    sa.Column('ringcentral_extension_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_email'), 'agents', ['email'], unique=False)
    op.create_index(op.f('ix_agents_livechat_agent_id'), 'agents', ['livechat_agent_id'], unique=True)
    op.create_index(op.f('ix_agents_ringcentral_extension_id'), 'agents', ['ringcentral_extension_id'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('livechat_customer_id', sa.String(length=255), nullable=True),
    sa.Column('ringcentral_contact_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_livechat_customer_id'), 'customers', ['livechat_customer_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_ringcentral_contact_id'), 'customers', ['ringcentral_contact_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_type', sa.String(length=100), nullable=False),
    sa.Column('source_platform', sa.String(length=20), nullable=False),
    sa.Column('target_platform', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_log_status_created', 'sync_logs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_sync_logs_agent_id'), 'sync_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_conversation_id'), 'sync_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_created_at'), 'sync_logs', ['created_at'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('webhook_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_platform_type', 'webhook_events', ['platform', 'event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_expires_at'), 'webhook_events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_webhook_events_processed'), 'webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_events_webhook_id'), 'webhook_events', ['webhook_id'], unique=True)
    op.create_table('agent_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('livechat_status', sa.String(length=50), nullable=False),
    sa.Column('ringcentral_presence', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_state_changed', 'agent_states', ['agent_id', 'state_changed_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_type', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('livechat_chat_id', sa.String(length=255), nullable=True),
    sa.Column('ringcentral_session_id', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_agent_status', 'conversations', ['agent_id', 'status'], unique=False)
    op.create_index('idx_conversation_started', 'conversations', ['started_at'], unique=False)
    op.create_index(op.f('ix_conversations_livechat_chat_id'), 'conversations', ['livechat_chat_id'], unique=False)
    op.create_index(op.f('ix_conversations_ringcentral_session_id'), 'conversations', ['ringcentral_session_id'], unique=False)
    op.create_table('call_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('from_number', sa.String(length=50), nullable=True),
    sa.Column('to_number', sa.String(length=50), nullable=True),
    sa.Column('call_status', sa.String(length=50), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('recording_duration', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_records_session_id'), 'call_records', ['session_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('synced_to_livechat', sa.Boolean(), nullable=False),
    sa.Column('synced_to_ringcentral', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_sent', 'messages', ['conversation_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_messages_external_message_id'), 'messages', ['external_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_external_message_id'), table_name='messages')
    op.drop_index('idx_message_conversation_sent', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_call_records_session_id'), table_name='call_records')
    op.drop_table('call_records')
    op.drop_index(op.f('ix_conversations_ringcentral_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_livechat_chat_id'), table_name='conversations')
    op.drop_index('idx_conversation_started', table_name='conversations')
    op.drop_index('idx_conversation_agent_status', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_agent_state_changed', table_name='agent_states')
    op.drop_table('agent_states')
    op.drop_index(op.f('ix_webhook_events_webhook_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processed'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_expires_at'), table_name='webhook_events')
    op.drop_index('idx_webhook_platform_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_sync_logs_created_at'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_conversation_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_agent_id'), table_name='sync_logs')
    op.drop_index('idx_sync_log_status_created', table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_customers_ringcentral_contact_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_livechat_customer_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_agents_ringcentral_extension_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_livechat_agent_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_email'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
